- name: creates directory for backend
  file:
    path: ~/backend
    state: directory

- name: unarchive artifact.tar.gz
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: npm install
  command: npm install
  args:
    chdir: ~/backend

- name: pm2 start npm -- start
  command: pm2 start npm -- start
  args:
    chdir: ~/backend

- name: pm2 start -f ./main.js
  command: pm2 start -f ./main.js
  ignore_errors: yes
  args:
    chdir: ~/backend/dist
