- name: creates directory for backend
  file:
    path: ~/backend
    state: directory

- name: unarchive artifact.tar.gz
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: pm2 stop default
  command: pm2 stop default
  ignore_errors: yes
  args:
    chdir: ~/backend

- name: pm2 start npm -- start
  command: pm2 start npm -- start
  args:
    chdir: ~/backend
# - name: pm2 start main.js
#   become: true
#   command: pm2 start -f main.js
#   args:
#     chdir: ~/backend/dist
